# Generated by Django 5.0.6 on 2024-06-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.CharField(blank=True, null=True),
        ),
    ]
