# Generated by Django 5.0.6 on 2024-06-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_faction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'managed': False},
        ),
    ]
