# Generated by Django 5.0.6 on 2024-06-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_options_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='character',
            table='characters_character',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='characters_skill',
        ),
    ]
