# Generated by Django 5.0.6 on 2024-06-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apparel',
        ),
    ]
