# Generated by Django 5.0.6 on 2024-06-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_delete_apparel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArmorMods',
        ),
    ]
