# Generated by Django 5.0.6 on 2024-06-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0003_delete_armormods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planets',
        ),
    ]
