# Generated by Django 5.0.6 on 2024-06-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0004_delete_planets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Systems',
        ),
    ]
