# Generated by Django 5.0.6 on 2024-06-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('gravity', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('atmosphere', models.CharField(blank=True, max_length=50, null=True)),
                ('magnetosphere', models.CharField(blank=True, max_length=50, null=True)),
                ('water', models.CharField(blank=True, max_length=50, null=True)),
                ('biomes', models.TextField(blank=True, null=True)),
                ('traits', models.TextField(blank=True, null=True)),
                ('fauna', models.TextField(blank=True, null=True)),
                ('flora', models.TextField(blank=True, null=True)),
                ('resources', models.TextField(blank=True, null=True)),
                ('planet_length', models.CharField(blank=True, max_length=50, null=True)),
                ('domesticable', models.TextField(blank=True, null=True)),
                ('hab_rank', models.TextField(blank=True, null=True)),
                ('gatherable', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'systems',
                'managed': False,
            },
        ),
    ]
