# Generated by Django 5.0.6 on 2024-07-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('work_bench', models.CharField(max_length=100)),
                ('special_projects_rank', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CraftingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('manufactured_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crafting_materials', to='planets.manufactureditem')),
            ],
        ),
    ]
