# Generated by Django 5.0.6 on 2024-07-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_manufactureditem_craftingmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftingmaterial',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='manufactureditem',
            options={'managed': False},
        ),
    ]
