# Generated by Django 5.0.6 on 2024-07-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_alter_craftingmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='craftingmaterial',
            table='items_manufactureditem',
        ),
        migrations.AlterModelTable(
            name='manufactureditem',
            table='items_craftingmaterial',
        ),
    ]
