# Generated by Django 5.0.6 on 2024-07-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_alter_craftingmaterial_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='craftingmaterial',
            table='items_craftingmaterial',
        ),
        migrations.AlterModelTable(
            name='manufactureditem',
            table='items_manufactureditem',
        ),
    ]
